
# nfqws Android build script source of truth is nfqws-android-build.sh
#!/bin/bash
# Cross-compiles nfqws (bol-van/zapret) for Android: libmnl + libnfnetlink +
# libnetfilter_queue (static) -> static nfqws binary. Usage: bash build_nfqws.sh <abi>
set -e
ABI=$1
export NDK=/c/Users/roman/dev-tools/android-sdk/ndk/25.1.8937393
TC="$NDK/toolchains/llvm/prebuilt/windows-x86_64/bin"
B=/tmp/zbuild
SYS=$B/sysroot-$ABI/usr/local
CFLAGS="-std=gnu99 -Os -ffunction-sections -fdata-sections -DANDROID"

case $ABI in
  arm64-v8a) TRIPLE=aarch64-linux-android23 ;;
  armeabi-v7a) TRIPLE=armv7a-linux-androideabi23 ;;
  *) echo "unknown abi"; exit 1 ;;
esac
CC="$TC/$TRIPLE-clang"
AR="$TC/llvm-ar"

mkdir -p "$SYS/lib" "$SYS/include"

# --- libmnl (config.h generated by an earlier autotools run in-tree) ---
cd "$B/libmnl-1.0.5"
$CC $CFLAGS -Isrc -Iinclude -I. -c src/socket.c src/callback.c src/nlmsg.c src/attr.c
$AR rcs "$SYS/lib/libmnl.a" socket.o callback.o nlmsg.o attr.o
cp -r include/libmnl "$SYS/include/"

# --- libnfnetlink ---
cd "$B/libnfnetlink-1.0.2"
$CC $CFLAGS -Iinclude -Isrc -c src/libnfnetlink.c src/iftable.c src/rtnl.c
$AR rcs "$SYS/lib/libnfnetlink.a" libnfnetlink.o iftable.o rtnl.o
cp -r include/libnfnetlink "$SYS/include/"
# Forward the bundled kernel header to the NDK one (enum double-definition).
cat > "$SYS/include/libnfnetlink/linux_nfnetlink.h" << 'EOF'
/* Forwarding header for Android NDK builds: the kernel UAPI header carries
 * the same definitions, guarded by _UAPI_NFNETLINK_H. */
#ifndef _LINUX_NFNETLINK_USERSPACE_H
#define _LINUX_NFNETLINK_USERSPACE_H
#include <linux/netfilter/nfnetlink.h>
#endif
EOF

# --- libnetfilter_queue (config.h + patched tcp.c/pktbuff.c/ipv4.c in-tree) ---
cd "$B/libnetfilter_queue-1.0.5"
$CC $CFLAGS -Iinclude -Isrc -I. -I"$SYS/include" -c src/libnetfilter_queue.c src/nlmsg.c \
    src/extra/checksum.c src/extra/ipv6.c src/extra/tcp.c src/extra/ipv4.c \
    src/extra/pktbuff.c src/extra/udp.c
$AR rcs "$SYS/lib/libnetfilter_queue.a" libnetfilter_queue.o nlmsg.o \
    checksum.o ipv6.o tcp.o ipv4.o pktbuff.o udp.o
cp -r include/libnetfilter_queue "$SYS/include/"

# --- nfqws ---
cd "$B/../zapret-src/zapret/nfq"
rm -f nfqws nfqws-*.o crypto/*.o
$CC $CFLAGS -I"$SYS/include" -o "nfqws-$ABI" *.c crypto/*.c \
    -L"$SYS/lib" -lz -lnetfilter_queue -lnfnetlink -lmnl -llog \
    -Wl,--gc-sections -Wl,-s
"$TC/llvm-strip" "nfqws-$ABI"
mkdir -p "$B/out/$ABI"
cp "nfqws-$ABI" "$B/out/$ABI/nfqws"
echo "BUILD_OK $ABI: $(stat -c %s "nfqws-$ABI") bytes"
